export enum StagesOfGrowth {
    GERMINATION,
    TRANSPLANTING,
    VEGETATIVE_GROWTH,
    HEAD_FORMATION,
    BULBING,
    BOLTING,
    SPROUTING,
    EARLY_SPROUTING,
    HARVEST,
    MATURITY,
    FLOWERING,
    FRUIT_FORMATION
}
