package com.xplug.tech.enums;

public enum PolicyStatus {
    ACTIVE, INACTIVE, SUSPENDED, REJECTED, BLACKLISTED, PENDING_AUTHORISATION, WAITING_REVIEW, TERMINATED, TERMINATION_PENDING, PENDING_SUSPENSION, PENDING_REACTIVATION, DELETED
}
